<a href="https://colab.research.google.com/github/asterinwl/Tensorflow/blob/master/boston%26iris_pred_Hidden.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **보스턴 집값**

 ## 1.과거의 데이터를 준비합니다

In [1]:
import pandas as pd

In [2]:
보스턴=pd.read_csv('boston.csv')
보스턴.head()

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [3]:
독립=보스턴[['crim','zn','indus','chas','nox','rm','age','dis','rad','tax','ptratio','b','lstat']]
종속=보스턴[['medv']]
print(독립.shape,종속.shape)

(506, 13) (506, 1)


# 2.모델의 구조를 만듭니다

In [4]:
import tensorflow as tf

In [5]:
X=tf.keras.layers.Input(shape=[13])
H=tf.keras.layers.Dense(10,activation='swish')(X)
Y=tf.keras.layers.Dense(1)(H)
model=tf.keras.models.Model(X,Y)
model.compile(loss='mse')

독립변수는 13개고 종속변수는 1개이므로 X는 shape가 13,Y는 Dense가 1이다.

Hidden을 써야지 더 좋은 결과값을 구할 수 있다.

In [6]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


# 3.데이터로 모델을 학습(FIT)합니다.

In [7]:
model.fit(독립,종속,epochs=10)

Epoch 1/10
16/16 [==============================] - 1s 2ms/step - loss: 20187.1797
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 10257.7197
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 5402.7578
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 3016.4614
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 2015.0549
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 1464.9175
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 1068.1583
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 789.7278
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 622.7561
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 516.8416


In [8]:
model.fit(독립,종속,epochs=1000, verbose=0)

verbose=0은 결과값을 보지 않겠다는 의미이다.

# 4.모델을 이용합니다.

In [9]:
print("Predictions: ",model.predict(독립[0:5]))

Predictions:  [[33.581112]
 [26.80545 ]
 [32.9733  ]
 [32.551548]
 [31.132929]]


1행부터 5행까지의 medv의 값을 추측해보았다.

In [10]:
종속[0:5]

medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

실제 1행부터 5행까지의 medv의 값이다. 차이가 존재함을 알 수 있다.

# 5.모델의 수식 확인

In [11]:
model.get_weights()

[array([[ 1.21721916e-01,  1.89218357e-01,  2.30810985e-01,
         -4.51219738e-01, -5.75483926e-02,  6.33397922e-02,
         -5.18467963e-01,  1.44545287e-01, -8.80542547e-02,
          5.20455182e-01],
        [-2.78196216e-01, -2.24475294e-01,  2.44741917e-01,
          3.92723739e-01,  3.21783461e-02, -1.97703131e-02,
          5.64114571e-01,  1.41449153e-01,  1.42850742e-01,
          2.33351812e-01],
        [ 6.94229007e-01,  3.48482758e-01, -2.63919860e-01,
          8.90460610e-02,  2.17781737e-01, -1.54535532e-01,
          1.05190113e-01, -4.36384857e-01, -2.04971135e-01,
         -5.90907216e-01],
        [ 1.83854520e+00,  1.70472503e+00, -4.88640040e-01,
          3.81455839e-01, -1.28966820e+00,  5.69629967e-01,
          1.88733184e+00, -1.48187414e-01,  2.18729639e+00,
         -2.14066195e+00],
        [-2.51565367e-01,  2.96972781e-01,  4.39234614e-01,
          2.27896631e-01, -7.24868894e-01, -5.66691160e-01,
          7.89380968e-01, -1.14340395e-01,  6.036984

# **아이리스 품종**

# 1.과거의 데이터를 준비합니다

In [12]:
import pandas as pd

In [18]:
아이리스=pd.read_csv('iris.csv')
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [19]:
아이리스=pd.get_dummies(아이리스)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

get_dummies는 원-핫 인코딩을 하는 방법이다.

get_dummies를 통해서 품종을 컴퓨터가 알아서 3가지로 분류했다. 따라서 품종이 품종_setosa	품종_versicolor	품종_virginica로 나누어졌다.

In [20]:
독립=아이리스[['꽃잎길이','꽃잎폭','꽃받침길이','꽃받침폭']]
종속=아이리스[['품종_setosa','품종_versicolor','품종_virginica']]
print(독립.shape,종속.shape)

(150, 4) (150, 3)


# 2.모델의 구조를 만듭시다

In [21]:
import tensorflow as tf

In [22]:
X=tf.keras.layers.Input(shape=[4])
H=tf.keras.layers.Dense(8,activation='swish')(X)
H=tf.keras.layers.Dense(8,activation='swish')(H)
H=tf.keras.layers.Dense(8,activation='swish')(H)
Y=tf.keras.layers.Dense(3,activation='softmax')(H)
model=tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

Hidden을 사용하면 더 정확한 값을 알 수 있다.

구하고자 하는 값이 무엇이냐에 따라 loss를 다르게 둘 수 있다. 분류는 `loss='categorical_crossentropy'` 회귀는 `loss='mse'`이다.

분류는 회귀랑 다르게 `metrisc='accuracy'`를 통해 정확도를 구할 수 있다.

분류는 회귀보다 어렵다.

종속변수는 4개이고 독립변수는 3개라서 shape=4이고 Dense는 3개이다.

# 3.데이터로 모델을 학습(FIT)합니다

In [23]:
model.fit(독립,종속,epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 3ms/step - loss: 1.3651 - accuracy: 0.3467
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 1.2284 - accuracy: 0.5133
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1703 - accuracy: 0.6400
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1325 - accuracy: 0.6467
Epoch 5/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1038 - accuracy: 0.6533
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0801 - accuracy: 0.6133
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0575 - accuracy: 0.6200
Epoch 8/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0369 - accuracy: 0.5667
Epoch 9/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0115 - accuracy: 0.6000
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9812 - accuracy: 0.5267
Epoch 11/100
5/5 [===========

# 4.모델을 이용합니다

In [24]:
print(model.predict(독립[0:5]))

[[9.9889392e-01 1.1057670e-03 3.3826075e-07]
 [9.9810094e-01 1.8982588e-03 8.3449964e-07]
 [9.9810314e-01 1.8958352e-03 9.6102121e-07]
 [9.9657506e-01 3.4230652e-03 1.8669482e-06]
 [9.9879116e-01 1.2084906e-03 3.9354813e-07]]


예상값으로 가장 높은 값을 가진 1번이 정답이다.

In [25]:
print([종속[0:5]])

[   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0]


실제값과 비교해본 결과 예상값이 정답이다.

In [26]:
model.get_weights()

[array([[ 0.4794371 , -0.31855568,  0.17361635,  0.21320808,  0.7283301 ,
         -0.26719555,  0.09601051, -0.37025878],
        [-0.37284845, -0.5459526 , -0.4292771 ,  0.6924852 ,  0.3188045 ,
          0.19953777,  0.36687964,  0.36090475],
        [-0.10510007, -0.02277753, -0.49177897,  0.22820821, -0.72687477,
          0.14266019, -0.23808423, -0.13536039],
        [ 0.68921995,  0.3155265 , -0.20134814,  0.9402136 , -0.04913846,
          0.6640893 ,  0.03938363, -0.5265416 ]], dtype=float32),
 array([ 0.06360038, -0.09358461,  0.2564335 ,  0.05515893,  0.18189338,
         0.01209658, -0.11035939,  0.1924719 ], dtype=float32),
 array([[ 0.3189563 , -0.4212261 , -0.11147823, -0.2807619 ,  0.45436093,
          0.78701824,  0.4866682 , -0.08224535],
        [ 0.09541955, -0.6047042 ,  0.577375  , -0.32869047, -0.5890087 ,
          0.46610373, -0.5493901 ,  0.09459279],
        [-0.21367627,  0.21156862,  0.5641203 ,  0.17712606,  0.9243365 ,
          0.3745517 , -0.6814451 ,

모델에 가중치를 얼마나 넣었는지 확인하는 과정이다.