<a href="https://colab.research.google.com/github/asterinwl/Tensorflow/blob/master/boston%26iris_more_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **보스턴 집값**

 ## 1.과거의 데이터를 준비합니다

In [ ]:
import pandas as pd

In [ ]:
보스턴=pd.read_csv('boston.csv')
보스턴.head()

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [ ]:
독립=보스턴[['crim','zn','indus','chas','nox','rm','age','dis','rad','tax','ptratio','b','lstat']]
종속=보스턴[['medv']]
print(독립.shape,종속.shape)

(506, 13) (506, 1)


# 2.모델의 구조를 만듭니다

In [ ]:
import tensorflow as tf

In [ ]:
X=tf.keras.layers.Input(shape=[13])
H=tf.keras.layers.Dense(8,activation='swish')(X)
H=tf.keras.layers.Dense(8,activation='swish')(H)
H=tf.keras.layers.Dense(8,activation='swish')(H)
Y=tf.keras.layers.Dense(1)(H)
model=tf.keras.models.Model(X,Y)
model.compile(loss='mse')

Hidden을 써야지 더 좋은 결과값을 구할 수 있다.

독립변수는 13개고 종속변수는 1개이므로 X는 shape가 13,Y는 Dense가 1이다.

In [ ]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 8)                 112       
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 265
Trainable params: 265
Non-trainable params: 0
_________________________________________________________________


# 3.데이터로 모델을 학습(FIT)합니다.

In [ ]:
model.fit(독립,종속,epochs=10)

Epoch 1/10
16/16 [==============================] - 1s 1ms/step - loss: 384.1540
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 223.1074
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 109.0524
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 84.9218
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 82.0997
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 79.3527
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 77.3093
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 75.6235
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 74.8314
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 72.6995


In [ ]:
model.fit(독립,종속,epochs=1000, verbose=0)

verbose=0은 결과값을 보지 않겠다는 의미이다.

# 4.모델을 이용합니다.

In [ ]:
print("Predictions: ",model.predict(독립[0:5]))

Predictions:  [[34.42092 ]
 [24.13861 ]
 [33.15735 ]
 [36.141506]
 [30.770338]]


1행부터 5행까지의 medv의 값을 추측해보았다.

In [ ]:
종속[0:5]

medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

실제 1행부터 5행까지의 medv의 값이다. 차이가 존재함을 알 수 있다.

# 5.모델의 수식 확인

In [ ]:
model.get_weights()

[array([[ 0.13443147,  0.09368461, -1.3426118 , -0.48922008, -0.7122905 ,
         -0.33264363,  0.06799767,  0.35277888],
        [ 0.09111848, -0.02616287,  0.25219336, -0.4339781 ,  0.10044947,
          0.20569164,  0.19607258, -0.42219767],
        [ 0.50925016,  0.40927696,  0.2562453 ,  0.3875904 ,  0.7803589 ,
          0.03974652,  0.14868455,  0.26462504],
        [-0.08364642,  2.1217506 ,  2.327612  ,  0.48680514, -1.2510738 ,
         -0.28259915, -1.0496683 ,  0.08822957],
        [ 0.255692  , -0.21820566, -0.05825402, -0.13180938, -0.05332886,
          0.49046916,  0.12249324,  0.11983208],
        [-0.455497  ,  0.71959335,  2.312286  ,  0.28519726, -2.09539   ,
         -0.1171892 ,  0.1250802 , -0.5487464 ],
        [ 0.35302714,  0.02437923,  0.22355674, -0.18263069,  0.13287258,
          0.28644252,  0.20525908, -0.22780155],
        [-0.18009463, -0.4237345 , -0.4046592 ,  0.14087123,  1.1467487 ,
         -0.34872603, -0.7566475 ,  0.00806966],
        [ 0.2970

# 다른 코드로 Try Again

# 중간에 더 많은 코드를 집어넣는 것이 더 좋은 값을 만든다

In [ ]:
X=tf.keras.layers.Input(shape=[13])
H=tf.keras.layers.Dense(8)(X)
H=tf.keras.layers.BatchNormalization()(H)
H=tf.keras.layers.Dense(8,activation='swish')(X)

H=tf.keras.layers.Dense(8)(H)
H=tf.keras.layers.BatchNormalization()(H)
H=tf.keras.layers.Dense(8,activation='swish')(H)

H=tf.keras.layers.Dense(8)(H)
H=tf.keras.layers.BatchNormalization()(H)
H=tf.keras.layers.Dense(8,activation='swish')(H)

Y=tf.keras.layers.Dense(1)(H)
model=tf.keras.models.Model(X,Y)
model.compile(loss='mse')

In [ ]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 112       
_________________________________________________________________
dense_6 (Dense)              (None, 8)                 72        
_________________________________________________________________
batch_normalization_1 (Batch (None, 8)                 32        
_________________________________________________________________
dense_7 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 72        
_________________________________________________________________
batch_normalization_2 (Batch (None, 8)                 32  

# 3.데이터로 모델을 학습(FIT)합니다.

In [ ]:
model.fit(독립,종속,epochs=10)

Epoch 1/10
16/16 [==============================] - 1s 2ms/step - loss: 570.9482
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 538.7736
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 515.5694
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 496.7398
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 479.5005
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 463.8770
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 446.7076
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 430.1195
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 412.2052
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 392.9471


In [ ]:
model.fit(독립,종속,epochs=1000, verbose=0)

verbose=0은 결과값을 보지 않겠다는 의미이다.

# 4.모델을 이용합니다.

In [ ]:
print("Predictions: ",model.predict(독립[0:5]))

Predictions:  [[24.949722]
 [22.214926]
 [29.56082 ]
 [33.518044]
 [30.386007]]


1행부터 5행까지의 medv의 값을 추측해보았다.

In [ ]:
종속[0:5]

medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

실제 1행부터 5행까지의 medv의 값이다. 차이가 존재함을 알 수 있다.

# 5.모델의 수식 확인

In [ ]:
model.get_weights()

[array([[ 7.85566345e-02,  1.16317468e-02,  9.83302951e-01,
         -6.78936660e-01,  2.51083493e-01, -1.34550095e-01,
         -5.40286675e-02,  4.31193650e-01],
        [-6.73064515e-02,  3.47444713e-01, -3.89087617e-01,
          6.29719496e-02, -4.24987197e-01, -3.90835047e-01,
         -1.20998815e-01,  2.52294183e-01],
        [-1.18829638e-01, -5.75847216e-02,  2.24432582e-03,
         -2.53916293e-01, -2.90443242e-01,  8.10512304e-02,
          4.20250833e-01,  2.06425846e-01],
        [ 8.86089802e-01, -1.26013374e+00,  1.11203837e+00,
          8.79014194e-01, -1.56280994e-02,  1.36238158e-01,
          1.45125139e+00,  5.46212673e-01],
        [-1.07381463e+00, -9.57083583e-01, -4.20594364e-01,
         -1.09412706e+00,  3.09064031e-01, -1.58057176e-02,
         -7.90973127e-01,  1.21240842e+00],
        [ 2.06198168e+00,  3.83259320e+00,  1.62763262e+00,
          2.23666787e+00, -4.15738761e-01,  5.21562874e-01,
         -2.83145815e-01, -1.75076947e-01],
        [-5.0395

# **아이리스 품종**

# 1.과거의 데이터를 준비합니다

In [19]:
import pandas as pd

In [20]:
아이리스=pd.read_csv('iris.csv')
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [21]:
아이리스=pd.get_dummies(아이리스)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

get_dummies는 원-핫 인코딩을 하는 방법이다.

get_dummies를 통해서 품종을 컴퓨터가 알아서 3가지로 분류했다. 따라서 품종이 품종_setosa	품종_versicolor	품종_virginica로 나누어졌다.

In [22]:
독립=아이리스[['꽃잎길이','꽃잎폭','꽃받침길이','꽃받침폭']]
종속=아이리스[['품종_setosa','품종_versicolor','품종_virginica']]
print(독립.shape,종속.shape)

(150, 4) (150, 3)


# 2.모델의 구조를 만듭시다

In [23]:
import tensorflow as tf

In [24]:
X=tf.keras.layers.Input(shape=[4])
H=tf.keras.layers.Dense(8,activation='swish')(X)
H=tf.keras.layers.Dense(8,activation='swish')(H)
H=tf.keras.layers.Dense(8,activation='swish')(H)
Y=tf.keras.layers.Dense(3,activation='softmax')(H)
model=tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

Hidden을 사용하면 더 정확한 값을 알 수 있다.

구하고자 하는 값이 무엇이냐에 따라 loss를 다르게 둘 수 있다. 분류는 `loss='categorical_crossentropy'` 회귀는 `loss='mse'`이다.

분류는 회귀랑 다르게 `metrisc='accuracy'`를 통해 정확도를 구할 수 있다.

분류는 회귀보다 어렵다.

종속변수는 4개이고 독립변수는 3개라서 shape=4이고 Dense는 3개이다.

# 3.데이터로 모델을 학습(FIT)합니다

In [25]:
model.fit(독립,종속,epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 3ms/step - loss: 1.4375 - accuracy: 0.2867
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 1.3076 - accuracy: 0.3267
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 1.2359 - accuracy: 0.3333
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1816 - accuracy: 0.3333
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1412 - accuracy: 0.3333
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1069 - accuracy: 0.3333
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0749 - accuracy: 0.3333
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0449 - accuracy: 0.3333
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0134 - accuracy: 0.3333
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9826 - accuracy: 0.3333
Epoch 11/100
5/5 [===========

# 4.모델을 이용합니다

In [26]:
print(model.predict(독립[0:5]))

[[9.9932718e-01 5.5094077e-08 6.7282910e-04]
 [9.9821883e-01 7.1735712e-07 1.7804264e-03]
 [9.9876380e-01 2.8791371e-07 1.2360221e-03]
 [9.9802554e-01 9.4210765e-07 1.9735789e-03]
 [9.9939871e-01 4.1786247e-08 6.0129096e-04]]


예상값으로 가장 높은 값을 가진 1번이 정답이다.

In [27]:
print([종속[0:5]])

[   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0]


실제값과 비교해본 결과 예상값이 정답이다.

In [28]:
model.get_weights()

[array([[ 0.13877858,  0.00898524,  0.07845198,  0.6746145 ,  0.2819284 ,
         -0.47049698, -0.15996869,  0.4677969 ],
        [ 0.8060351 , -0.45464605, -0.34601906, -0.2608131 ,  0.7525137 ,
          0.46025646,  0.8039933 ,  0.35541627],
        [-0.53018063, -0.1399483 ,  0.17296141,  0.29980654, -0.66751605,
         -0.34551036,  0.03827936,  0.81431156],
        [ 0.03302073,  0.14333083,  0.8275792 , -0.6743969 ,  0.4314418 ,
          0.16813965, -0.59295434,  0.5496951 ]], dtype=float32),
 array([ 0.2704806 , -0.1375452 ,  0.06018865,  0.10523448,  0.1158841 ,
         0.22492957,  0.13397056, -0.10062194], dtype=float32),
 array([[-0.6986734 ,  0.14472534, -0.01312357,  0.5476893 ,  0.04799527,
          0.6479408 ,  0.31289843,  0.37413725],
        [-0.3082285 , -0.5706263 , -0.4834642 , -0.7373366 ,  0.24723199,
          0.17094436, -0.29834837, -0.10287318],
        [ 0.5002236 , -0.36171117, -0.44534454, -0.58359474,  0.02707289,
         -0.2621951 , -0.6537826 ,

모델에 가중치를 얼마나 넣었는지 확인하는 과정이다.

# 다른 코드로 Try Again

# 중간에 더 많은 코드를 집어넣는 것이 더 좋은 값을 만든다

In [29]:
X=tf.keras.layers.Input(shape=[4])
H=tf.keras.layers.Dense(8)(X)
H=tf.keras.layers.BatchNormalization()(H)
H=tf.keras.layers.Activation('swish')(H)

H=tf.keras.layers.Dense(8)(H)
H=tf.keras.layers.BatchNormalization()(H)
H=tf.keras.layers.Activation('swish')(H)

H=tf.keras.layers.Dense(8)(H)
H=tf.keras.layers.BatchNormalization()(H)
H=tf.keras.layers.Activation('swish')(H)

Y=tf.keras.layers.Dense(3,activation='softmax')(H)
model=tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

Hidden을 사용하면 더 정확한 값을 알 수 있다.

구하고자 하는 값이 무엇이냐에 따라 loss를 다르게 둘 수 있다. 분류는 `loss='categorical_crossentropy'` 회귀는 `loss='mse'`이다.

분류는 회귀랑 다르게 `metrisc='accuracy'`를 통해 정확도를 구할 수 있다.

분류는 회귀보다 어렵다.

종속변수는 4개이고 독립변수는 3개라서 shape=4이고 Dense는 3개이다.

# 3.데이터로 모델을 학습(FIT)합니다

In [30]:
model.fit(독립,종속,epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 3ms/step - loss: 1.6092 - accuracy: 0.0400
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 1.4808 - accuracy: 0.1000
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 1.4059 - accuracy: 0.1200
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 1.3205 - accuracy: 0.2000
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 1.2746 - accuracy: 0.2733
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1863 - accuracy: 0.4200
Epoch 7/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1261 - accuracy: 0.4800
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0427 - accuracy: 0.5867
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0042 - accuracy: 0.6000
Epoch 10/100
5/5 [==============================] - 0s 3ms/step - loss: 0.9706 - accuracy: 0.6267
Epoch 11/100
5/5 [===========

# 4.모델을 이용합니다

In [31]:
print(model.predict(독립[0:5]))

[[9.9872738e-01 7.7172316e-04 5.0089473e-04]
 [9.9850070e-01 1.0256000e-03 4.7376109e-04]
 [9.9935561e-01 3.7681058e-04 2.6759240e-04]
 [9.9877268e-01 8.1657380e-04 4.1079492e-04]
 [9.9900407e-01 5.4539007e-04 4.5056365e-04]]


예상값으로 가장 높은 값을 가진 1번이 정답이다.

In [32]:
print([종속[0:5]])

[   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0]


실제값과 비교해본 결과 예상값이 정답이다.

In [33]:
model.get_weights()

[array([[ 0.0357992 ,  0.47519907, -0.02940656, -0.25601143, -0.04137721,
         -0.32155812, -0.10843134,  0.04424128],
        [ 0.37529713, -0.18625948,  0.24235705,  0.34637836, -0.42388007,
         -0.07130403,  0.11883364, -0.5164849 ],
        [ 0.11521164,  0.2779927 , -0.31667733, -0.31534013,  0.3911621 ,
          0.5872142 , -0.31198323, -0.75738865],
        [ 0.579313  , -0.63426805,  0.20104341, -0.8632307 ,  0.03707255,
         -0.6446731 ,  0.4354056 , -0.07791865]], dtype=float32),
 array([-0.00500258,  0.00062235, -0.00217303, -0.00169796,  0.00577644,
         0.00086153,  0.00601756,  0.004927  ], dtype=float32),
 array([0.91090345, 0.8556691 , 0.9278345 , 1.0475839 , 1.169828  ,
        0.87205726, 0.9890626 , 1.0705273 ], dtype=float32),
 array([ 0.03579813, -0.16776852, -0.1624426 ,  0.00700518,  0.04333006,
         0.14064579,  0.14191172,  0.10582705], dtype=float32),
 array([ 2.5370362 ,  2.745801  , -0.29513964, -2.588255  , -0.04519401,
        -0.4487

모델에 가중치를 얼마나 넣었는지 확인하는 과정이다.