<a href="https://colab.research.google.com/github/asterinwl/Tensorflow/blob/master/iris_pred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.과거의 데이터를 준비합니다

In [4]:
import pandas as pd

In [5]:
아이리스=pd.read_csv('iris.csv')
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [6]:
아이리스=pd.get_dummies(아이리스)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

get_dummies는 원-핫 인코딩을 하는 방법이다.

get_dummies를 통해서 품종을 컴퓨터가 알아서 3가지로 분류했다. 따라서 품종이 품종_setosa	품종_versicolor	품종_virginica로 나누어졌다.

In [7]:
독립=아이리스[['꽃잎길이','꽃잎폭','꽃받침길이','꽃받침폭']]
종속=아이리스[['품종_setosa','품종_versicolor','품종_virginica']]
print(독립.shape,종속.shape)

(150, 4) (150, 3)


# 2.모델의 구조를 만듭시다

In [8]:
import tensorflow as tf

In [10]:
X=tf.keras.layers.Input(shape=[4])
Y=tf.keras.layers.Dense(3,activation='softmax')(X)
model=tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

구하고자 하는 값이 무엇이냐에 따라 loss를 다르게 둘 수 있다. 분류는 `loss='categorical_crossentropy'` 회귀는 `loss='mse'`이다.

분류는 회귀랑 다르게 `metrisc='accuracy'`를 통해 정확도를 구할 수 있다.

분류는 회귀보다 어렵다.

종속변수는 4개이고 독립변수는 3개라서 shape=4이고 Dense는 3개이다.

# 3.데이터로 모델을 학습(FIT)합니다

In [11]:
model.fit(독립,종속,epochs=1000)

Epoch 1/1000
5/5 [==============================] - 0s 3ms/step - loss: 3.4532 - accuracy: 0.3667
Epoch 2/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.3856 - accuracy: 0.3933
Epoch 3/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.3393 - accuracy: 0.4600
Epoch 4/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.2981 - accuracy: 0.4800
Epoch 5/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.2598 - accuracy: 0.5200
Epoch 6/1000
5/5 [==============================] - 0s 3ms/step - loss: 3.2237 - accuracy: 0.5400
Epoch 7/1000
5/5 [==============================] - 0s 3ms/step - loss: 3.1893 - accuracy: 0.5400
Epoch 8/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.1545 - accuracy: 0.5200
Epoch 9/1000
5/5 [==============================] - 0s 2ms/step - loss: 3.1188 - accuracy: 0.4867
Epoch 10/1000
5/5 [==============================] - 0s 3ms/step - loss: 3.0845 - accuracy: 0.4867
Epoch 11/1000
5/5 [

# 4.모델을 이용합니다

In [14]:
print(model.predict(독립[0:5]))

[[9.9870300e-01 1.2968926e-03 1.1769822e-07]
 [9.9499172e-01 5.0072372e-03 1.0935006e-06]
 [9.9781644e-01 2.1832245e-03 3.7661877e-07]
 [9.9454224e-01 5.4561729e-03 1.5923428e-06]
 [9.9899560e-01 1.0042900e-03 8.7182677e-08]]


예상값으로 가장 높은 값을 가진 1번이 정답이다.

In [15]:
print([종속[0:5]])

[   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0]


실제값과 비교해본 결과 예상값이 정답이다.

In [16]:
model.get_weights()

[array([[ 0.47794443,  0.37120098, -0.56588596],
        [ 2.6249142 , -0.04166152, -1.4230312 ],
        [-3.9346998 , -0.72520983,  0.7444733 ],
        [-2.914997  , -0.83252686,  2.2380168 ]], dtype=float32),
 array([ 2.228737 ,  0.5498771, -1.8152078], dtype=float32)]

모델에 가중치를 얼마나 넣었는지 확인하는 과정이다.